[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"
via_ir = true
optimizer = true
optimizer_runs = 200
[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/sUw2f_qi4BEhxg0RwpyX-"
local = "http://127.0.0.1:8545"

# 添加私钥配置
[profile.default.env]
PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
DEFAULT_SENDER = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"

# 开发环境配置
[profile.dev]
solc_version = "0.8.25"
via_ir = true
optimizer_runs = 0  # 关闭优化器加快编译速度

# 生产环境配置
[profile.prod]
solc_version = "0.8.25"
via_ir = true
optimizer_runs = 10_000  # 更高优化级别



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
